###
POST http://localhost:3003/docentes
Content-Type: application/json

{
    "nome": "Sherman Klump",
    "email": "professoraloprado@labenu.com.br",
    "data_nasc": "1996/06/28",
    "turma_id": "2"
}

###
GET http://localhost:3003/docentes

###
PUT http://localhost:3003/docentes/287555eb-2983-4802-88dd-6b8b358cee7d
Content-Type: application/json

{
    "turma_id": "1"
}

###
POST http://localhost:3003/turma
Content-Type: application/json

{
    "nome": "teste5",
    "modulo": 2
}

###  // insere estudante na tabela
POST  http://localhost:3003/addEstudante
Content-Type: application/json 

{
	"nome": "EstudanteXXXXX",
	"email": "estuXXXX@email.com",
	"data_nasc": "2020/01/01",
    "turma_id": "1"
}

###  // buscar estudante pelo nome
GET http://localhost:3003/estudante/estudante2

###  // edita turma do estudante
PUT  http://localhost:3003/Estudante/edit/1652835837963
Content-Type: application/json 

{
    "turma_id": "1"
}

###  // buscar o estudante e seu respectivo hobby
GET http://localhost:3003/estudantes/